# MySQL DATABASE
version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: myapp-mysql # Đặt tên container
    restart: always # Tự khởi động lại container khi máy tắt or restart
    environment: # thiết lập các biến môi trường cho MySQL
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql # Lưu dữ liệu database vĩnh viễn (không bị mất khi tắt container).
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Copy file init.sql vào container và tự động chạy khi database khởi tạo lần đầu.
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myapp-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: devuser
      PMA_PASSWORD: devpass123
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data:




# nginx
version: '3.9'

services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./portal/public:/var/www/public
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - portal
      - api
      - internal-api

  portal:
    image: php:8.2-fpm
    volumes:
      - ./portal/public:/var/www/public

  api:
    image: php:8.2-fpm
    volumes:
      - ./api/public:/var/www/public

  internal-api:
    image: php:8.2-fpm
    volumes:
      - ./internal-api/public:/var/www/public