version: '3.8'

services:
  waf-proxy:
    image: bunkerity/bunkerweb:1.5.8
    container_name: ctf-waf
    # ports:
    #   - "80:8080"
    #   # - "443:8443" # Bị trùng cổng 443 với Wazuh Dashboard, tạm thời comment lại
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - API_WHITELIST_IP=127.0.0.0/8 172.16.0.0/12 192.168.0.0/16 10.0.0.0/8
      - MULTISITE=yes
      - USE_SERVE_FILES=no
      - SERVER_NAME=portal.lab.local staff.lab.local api.lab.local
      - PORTAL_LAB_LOCAL_USE_REVERSE_PROXY=yes
      - PORTAL_LAB_LOCAL_REVERSE_PROXY_URL=/
      - PORTAL_LAB_LOCAL_REVERSE_PROXY_HOST=http://portal:80
      - STAFF_LAB_LOCAL_USE_REVERSE_PROXY=yes
      - STAFF_LAB_LOCAL_REVERSE_PROXY_URL=/
      - STAFF_LAB_LOCAL_REVERSE_PROXY_HOST=http://staff:80
      - API_LAB_LOCAL_USE_REVERSE_PROXY=yes
      - API_LAB_LOCAL_REVERSE_PROXY_URL=/
      - API_LAB_LOCAL_REVERSE_PROXY_HOST=http://api:80
      - USE_MODSECURITY=yes
      - USE_MODSECURITY_CRS=yes
      - BAD_BEHAVIOR_THRESHOLD=10
      - USE_ANTIBOT=no
      - DNS_RESOLVERS=127.0.0.11
      - PORTAL_LAB_LOCAL_SERVE_FILES=no
      - STAFF_LAB_LOCAL_SERVE_FILES=no
      - API_LAB_LOCAL_SERVE_FILES=no
    volumes:
      - bw-data:/data
      - ./waf-proxy/custom-rules.conf:/data/configs/modsecurity/custom-rules.conf:ro
      - ./waf-proxy/configs/portal.lab.local:/data/configs/server-http/portal.lab.local:ro
      - ./waf-proxy/configs/staff.lab.local:/data/configs/server-http/staff.lab.local:ro
      - ./waf-proxy/configs/api.lab.local:/data/configs/server-http/api.lab.local:ro
    networks:
      - public-net
    restart: always

  waf-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.8
    container_name: ctf-waf-scheduler
    depends_on:
      - waf-proxy
      - waf-docker-proxy
    environment:
      - DOCKER_HOST=tcp://ctf-waf-docker-proxy:2375
    volumes:
      - bw-data:/data
    networks:
      - public-net
    restart: always

  waf-docker-proxy:
    image: tecnativa/docker-socket-proxy:nightly
    container_name: ctf-waf-docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1
    networks:
      - public-net
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - portal
      - api
      - staff
      - internal-api
      - waf-proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - nginx-logs:/var/log/nginx
    networks:
      public-net:
        aliases:
          - portal.lab.local
          - staff.lab.local
          - api.lab.local
          - cdn.lab.local
          - internal-api.lab.local
      private-net:
        aliases:
          - portal.lab.local
          - staff.lab.local
          - api.lab.local
          - cdn.lab.local
          - internal-api.lab.local
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3

  portal:
    build: ./portal
    volumes:
      - ./portal/src:/var/www/portal
      - php-sessions:/tmp/sessions
    networks:
      - public-net
      - private-net
    environment:
      DB_HOST: db
      DB_NAME: corpdb
      DB_USER: appuser
      DB_PASS: SuperSecret123!
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./api
    volumes:
      - ./api/src:/var/www/api
    networks:
      - public-net
      - private-net
    environment:
      DB_HOST: db
      DB_NAME: corpdb
      DB_USER: appuser
      DB_PASS: SuperSecret123!
    depends_on:
      db:
        condition: service_healthy

  staff:
    build: ./staff
    volumes:
      - ./staff/src:/var/www/staff
      - php-sessions:/tmp/sessions
      - nginx-logs:/var/log/nginx:ro
      - ./uploads:/var/www/uploads:ro
    networks:
      - public-net
      - private-net
    environment:
      DB_HOST: db
      DB_NAME: corpdb
      DB_USER: appuser
      DB_PASS: SuperSecret123!
    depends_on:
      db:
        condition: service_healthy

  internal-api:
    build: ./internal-api
    volumes:
      - ./internal-api/src:/var/www/internal-api
      - ./uploads:/var/www/uploads
      - ./cdn/auth.php:/var/www/uploads/auth.php:ro
      - ./cdn/internal.php:/var/www/uploads/internal.php:ro
      - php-sessions:/tmp/sessions
    # IMPORTANT: internal-api CHỈ nằm trong private-net — không accessible từ internet
    networks:
      - private-net
    environment:
      DB_HOST: db
      DB_NAME: corpdb
      DB_USER: appuser
      DB_PASS: SuperSecret123!
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: corpdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: SuperSecret123!
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    networks:
      - private-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "appuser", "-pSuperSecret123!"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  public-net:
    driver: bridge
  private-net:
    driver: bridge

volumes:
  db-data:
  nginx-logs:
  php-sessions:
  bw-data:
