server {
    listen 80;
    server_name cdn.lab.local;
    root /var/www/uploads;

    access_log /var/log/nginx/cdn_access.log detailed;
    error_log  /var/log/nginx/cdn_error.log;

    # VULN: Match any request containing .php (including .php.jpg) and execute as PHP
    # Thiếu block deny execution cho /uploads/ — có chủ ý
    location ~ \.php {
        fastcgi_pass internal-api:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/uploads$fastcgi_script_name;
        include fastcgi_params;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
