# cdn.lab.local đã bị ẩn khỏi mạng ngoài
# Chỉ có thể truy cập qua IP nội bộ 127.0.0.1:8888 trên container internal-api
#
# server {
#     listen 80;
#     server_name cdn.lab.local;
#
#     access_log /var/log/nginx/cdn_access.log detailed;
#     error_log  /var/log/nginx/cdn_error.log;
#
#     location / {
#         proxy_pass         http://internal-api:80;
#         proxy_set_header   Host              $host;
#         proxy_set_header   X-Real-IP         $remote_addr;
#         proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
#         proxy_read_timeout 10;
#     }
# }
