server {
    listen 80;
    server_name internal-api.lab.local internal-api;
    root /var/www/internal-api;
    index index.php;

    # Internal only — không accessible từ public internet
    # Chỉ reachable qua Docker private-net hoặc SSRF
    access_log /var/log/nginx/internal_access.log detailed;
    error_log  /var/log/nginx/internal_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass internal-api:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
