server {
    listen 80;
    server_name portal.lab.local;
    root /var/www/portal;
    index index.php;

    access_log /var/log/nginx/portal_access.log detailed;
    error_log  /var/log/nginx/portal_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass portal:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # VULN: Không có CSP header (có chủ ý — cho phép XSS chạy tự do)
    # VULN: Không có X-Frame-Options (có chủ ý)
}
