server {
    listen 80;
    server_name portal.lab.local;

    access_log /var/log/nginx/portal_access.log detailed;
    error_log  /var/log/nginx/portal_error.log;

    # VULN: Không có CSP header (có chủ ý — cho phép XSS chạy tự do)
    # VULN: Không có X-Frame-Options (có chủ ý)

    location / {
        proxy_pass         http://waf-proxy:8080;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 30;

        # Override BunkerWeb's CSP to allow form redirect to staff panel
        proxy_hide_header  Content-Security-Policy;
        add_header         Content-Security-Policy "object-src 'none'; form-action 'self' http://staff.lab.local; frame-ancestors 'self';" always;
    }
}
