server {
    listen 80;

    server_name api.lab.local;

    root /var/www/api/public;
    index index.php;

    access_log /var/log/nginx/api_access.log;
    error_log  /var/log/nginx/api_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass api:9000;

        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}