# 1. Chặn đứng các request cố tình đọc file flag trong bài CTF
SecRule ARGS "@contains flag" "id:100001,phase:2,deny,status:403,msg:'Dung co hòng doc file flag nhe!'"

# 2. Chặn các payload chứa ký tự lạ thường dùng trong lệnh RCE hệ thống
SecRule ARGS|REQUEST_HEADERS "@rx (?:whoami|cat\s+/etc/passwd|id|uname)" \
    "id:100002,phase:2,deny,status:406,msg:'Phát hiện hành vi cố gắng thực thi lệnh hệ thống RCE!'"

# 3. Giới hạn kích thước file upload (Tránh việc đối thủ upload file shell nặng làm treo máy)
SecRequestBodyLimit 1048576

# 4. rule ModSecurity đơn giản để chặn một số payload XSS
SecRule ARGS "@rx (?i)(<script|javascript:|onerror=|onload=|alert\s*\()" \
    "id:100006,phase:2,deny,status:403,msg:'Phát hiện XSS payload!'"
